// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN98ODMyAXuhiqtX5UfYeDXYcgq5dAVeg',
    appId: '1:1092273154641:web:1822acdcaa8bcf384b2670',
    messagingSenderId: '1092273154641',
    projectId: 'aid-iq-ae64b',
    authDomain: 'aid-iq-ae64b.firebaseapp.com',
    storageBucket: 'aid-iq-ae64b.firebasestorage.app',
    measurementId: 'G-Z946KM0WGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64pi4i9Fsz7EXpyVvdpfqr2weKxNaNpE',
    appId: '1:1092273154641:android:80177c74408eebc14b2670',
    messagingSenderId: '1092273154641',
    projectId: 'aid-iq-ae64b',
    storageBucket: 'aid-iq-ae64b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtjoLh9FqnLqm-XI9L57yYV4ItCF1eGw',
    appId: '1:1092273154641:ios:34ac73a8c67ae8444b2670',
    messagingSenderId: '1092273154641',
    projectId: 'aid-iq-ae64b',
    storageBucket: 'aid-iq-ae64b.firebasestorage.app',
    iosBundleId: 'com.example.aidIqDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtjoLh9FqnLqm-XI9L57yYV4ItCF1eGw',
    appId: '1:1092273154641:ios:34ac73a8c67ae8444b2670',
    messagingSenderId: '1092273154641',
    projectId: 'aid-iq-ae64b',
    storageBucket: 'aid-iq-ae64b.firebasestorage.app',
    iosBundleId: 'com.example.aidIqDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN98ODMyAXuhiqtX5UfYeDXYcgq5dAVeg',
    appId: '1:1092273154641:web:43ac1c66d22fc2874b2670',
    messagingSenderId: '1092273154641',
    projectId: 'aid-iq-ae64b',
    authDomain: 'aid-iq-ae64b.firebaseapp.com',
    storageBucket: 'aid-iq-ae64b.firebasestorage.app',
    measurementId: 'G-277HHEG140',
  );
}
